

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
   
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        

        <div class="row">
          <!-- /.col (left) -->
          <div class="col-md-6 offset-md-3">
            <div class="card card-primary card-outline">
             <form method="post">
              <?php View::content(); ?>
              <div class="card-body">
                <!-- Date -->
                <div class="form-group">
                  <label>Clave Actual</label>
                    <div class="input-group date" >
                        <input type="password" class="form-control datetimepicker-input" name="clave1" />
                        <div class="input-group-append">
                            <div class="input-group-text"><i class="text-primary fas fa-key"></i></div>
                        </div>
                    </div>
                </div>
                <!-- /.form group -->
                <div class="form-group">
                  <label>Nueva Clave</label>
                    <div class="input-group date" >
                        <input type="password" class="form-control datetimepicker-input" name="clave2" />
                        <div class="input-group-append">
                            <div class="input-group-text"><i class="text-primary fas fa-key"></i></div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                  <label>Repita La Clave</label>
                    <div class="input-group date" >
                        <input type="password" class="form-control datetimepicker-input" name="clave3" />
                        <div class="input-group-append">
                            <div class="input-group-text"><i class="text-primary fas fa-key"></i></div>
                        </div>
                    </div>
                </div>
              </div>
              <div class="card-footer">
                 <button type="submit" class="btn btn-primary">Cambiar Clave</button>
              </div>
            </form>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

          </div>
          <!-- /.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
<!-- ./wrapper -->
<script type="text/javascript">
  //Date range picker
  //  $('#reservationdate').datetimepicker({
  //      format: 'L'
  //  });
</script>


<!-- dP7uh8fI4> -->