

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        <div class="row">
          <!-- /.col (left) -->
          <div class="col-md-6 offset-md-3">
            <div class="card card-primary card-outline">
             <form method="post">
              <?php View::content(); ?>
              <div class="card-body">
                <!-- Date -->
                <div class="form-group">
                  <label>Nombre</label>
                    <div class="input-group date" >
                      <?php echo Form::text("a.nombre",'class="form-control datetimepicker-input" ' ); ?>
                        <div class="input-group-append">
                            <div class="input-group-text"><i class="far fa-address-book"></i></div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                  <label>Apellido</label>
                    <div class="input-group date" >
                      <?php echo Form::text("a.apellido",'class="form-control datetimepicker-input" ' ); ?>
                        <div class="input-group-append">
                            <div class="input-group-text"><i class="far fa-address-book"></i></div>
                        </div>
                    </div>
                </div>
                <!-- /.form group -->
                <div class="form-group">
                  <label>EMail</label>
                    <div class="input-group date" >
                      <?php echo Form::text("a.mail",'class="form-control datetimepicker-input" ' ); ?>
                        <div class="input-group-append">
                            <div class="input-group-text"><i class="far fa-envelope"></i></div>
                        </div>
                    </div>
                </div>
                <!-- /.form group -->
                <div class="form-group">
                  <label>Celular</label>
                    <div class="input-group date" >
                      <?php echo Form::text("a.celular",'class="form-control datetimepicker-input" ' ); ?>
                        <div class="input-group-append">
                            <div class="input-group-text"><i class="fas fa-mobile-alt"></i></div>
                        </div>
                    </div>
                </div>
              </div>

              <div class="card-footer">
                 <button type="submit" class="btn btn-primary">Actualizar Datos</button>
              </div>
            </form>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

          </div>
          <!-- /.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
<!-- ./wrapper -->
<script type="text/javascript">
  //Date range picker
  //  $('#reservationdate').datetimepicker({
  //      format: 'L'
  //  });
</script>


<!-- dP7uh8fI4> -->