  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#../../index3.html" class="brand-link">
      <img src="../../dist/img/AdminLTELogo.png"
           alt="AdminLTE Logo"
           class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Y mi Dinero?</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">

      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-header">SISTEMA</li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH;?>proyecto/index" class="nav-link">
              <i class="nav-icon far fa-folder-open text-warning"></i>
              <p>Proyectos Actuales</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH;?>proyecto/add" class="nav-link">
              <i class="nav-icon fas fa-folder-plus text-warning"></i>
              <p>Nuevo Proyecto </p>
            </a>
          </li>
          <li class="nav-header">DATOS PERSONALES</li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH?>usuario/datosp" class="nav-link">
              <i class="nav-icon far fa-circle text-danger"></i>
              <p class="text">Mis Datos</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH?>usuario/clave" class="nav-link">
              <i class="nav-icon far fa-circle text-warning"></i>
              <p>Cambiar Contrase&ntilde;a</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH?>usuario/foto" class="nav-link">
              <i class="nav-icon far fa-circle text-success"></i>
              <p>Foto de Perfil</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="<?php echo PUBLIC_PATH?>usuario/salir" class="nav-link">
              <i class="nav-icon far fa-circle text-info"></i>
              <p>Salir del Sistema</p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
