

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
   
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              
              <div class="col-md-6 offset-md-3">
                  <a href="<?php echo $linkAdd?>" class="btn btn-success">
                      <i class="fas fa-plus-square"></i>
                      Agregar Movimiento</a>
                  <a href="<?php echo $linkVolver?>" class="btn btn-warning">
                      <i class="fas fa-redo-alt"></i>
                      Volver</a>
              </div>
          </div>
          
          <div class="row">
              <div class="col-3"><small>Proyecto</small></div>
              <div class="col-9"><b><?php echo $a->proyecto_nombre;?></b></div>
          </div>
          
<div class="row">
    <?php foreach ($lista as $pro) { ?>

 <?php } ?>
</div>
 
      
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
<!-- ./wrapper -->
<script type="text/javascript">
  //Date range picker
  //  $('#reservationdate').datetimepicker({
  //      format: 'L'
  //  });
</script>


<!-- dP7uh8fI4> -->