

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
   
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <br>
          
<div class="row">
    <?php foreach ($lista as $pro) { ?>
          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box">
              <span class="info-box-icon bg-info elevation-1"><i class="fas fa-cog"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">
                    <?php echo $pro->proyecto_nombre;?> 
                        <?php echo $pro->proyecto_nombre;?> 
                </span>
                <span class="info-box-text"> </span>
                <span class="info-box-number">
                    <small>SALDO ACTUAL</small>
                  <i class="text-danger"> $</i>12767.98
                </span>
                <span class="info-box-number">
                  <small class="text-sm">SEGUIDORES</small>
                  <i class="text-danger"> #</i>5
                </span>
                <span class="info-box-text"> &nbsp;</span>
                <span class="info-box-more">
                <a href="<?php echo $linkMovi.$pro->id;?>" class="btn btn-warning btn-block">
                <i class="fas fa-dollar-sign"></i> 
                Movimientos
                </a>
                <!--<a href="" class="btn btn-primary btn-xs">Movimientos</a>-->
                </span>
                
              </div>
            </div>
<!--                <a href="<?php echo $linkEdit;?>" class="btn btn-warning"><i class="fas fa-edit"></i></a>
                <a href="<?php echo $linkDel;?>" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>-->

          </div>

 <?php } ?>
</div>
 
      
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
<!-- ./wrapper -->
<script type="text/javascript">
  //Date range picker
  //  $('#reservationdate').datetimepicker({
  //      format: 'L'
  //  });
</script>


<!-- dP7uh8fI4> -->